<h1>Signup Form</h1>
<form class="form" action="/index/save" method="post">
    <label for="name">Name:
        <input class="form-control" type="text" name="name" id="name">
    </label>
    <label for="email">Email:
        <input class="form-control" type="text" name="email" id="email">
    </label>
    <label for="password">Password:
        <input class="form-control" type="password" name="password" id="password">
    </label>
    <button class="btn btn-primary">Signup</button>
</form>